name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello_testbash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, TestBash!"
      - run: cd src/webapp/api
      - run: npm install
      - run: npm run test
