name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello_testbash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, TestBash!"
  run_api_tests:
    runs-on: ubuntu-latest
    needs: hello_testbash
    steps:
      - uses: actions/checkout@v1
      - name: Setup and run API tests
        working-directory: ./src/webapp/api
        run: |
          npm install
          npm run test
  run_ui_tests:
    runs-on: ubuntu-latest
    needs: hello_testbash
    steps:
      - uses: actions/checkout@v1
      - name: Spinning up environment
        working-directory: ./src/webapp
        run: |
          echo "Hello, again!"
          npm install
          npm run start-server
    #   - name: Setup and run UI tests
    #     working-directory: ./e2e
    #     run: |
    #       npm install
    #       npm run test